name: Chocolatine

on:
  push:
    branches: [ '**', '!ga-ignore-**' ]
  pull_request:
    branches: [ '**', '!ga-ignore-**' ]

jobs:
  check_repository_cleanliness:
    name: Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checks if the repository is clean
        run: |
          ERROR=0;
          for i in $(find ! -path "./.git/**" -name \* ! -name ".git" -type f);
          do
            if [[ "$(basename -- "$i")" =~ ^(#).*(#)$ ]]; then
              echo "::error file=${i:2},title=Unwanted file detected::${i:2}";
              ERROR=1;
            elif [[ "$(basename -- "$i")" =~ .*~ ]]; then
              echo "::error file=${i:2},title=Unwanted file detected::${i:2}";
              ERROR=1;
            elif [[ "$(basename -- "$i")" =~ .*pain_au_chocolat.* ]]; then
              echo "::error file=${i:2},title=Unwanted file detected::${i:2}";
              ERROR=1;
            elif [[ "$(basename -- "$i")" =~ .*(.o|.a|.so|.gcno|.gcda|.gcov)$ ]]; then
              echo "::error file=${i:2},title=Unwanted file detected::${i:2}";
              ERROR=1;
            fi
          done

          for i in $(find ! -path "./.git/**" -name \* ! -name ".git" -type d);
          do
            if [[ "$(basename -- "$i")" =~ .*tmp ]]; then
              for j in $(find -path "$i/*" -name \* -type f);
              do
                echo "::error file=${j:2},title=Unwanted file detected::${j:2}";
                ERROR=1;
              done
            fi
          done

          if [[ ERROR -eq 1 ]]; then
            exit 1;
          fi

  check_program_compilation:
    name: Checks if the program compiles correctly
    runs-on: ubuntu-latest
    needs: check_repository_cleanliness

    steps:
      - uses: actions/checkout@v3

      - name: Compilation
        run: |
          timeout 120 make

      - name: Clean temporary files
        run: |
          make clean

      - name: Checks executables
        run: |
          for i in $(echo $EXECUTABLES | tr "," " ");
          do
            if test -f "$i"; then
              if [[ "$(stat -c %a "$i")" =~ ^(5|7).* ]]; then
                echo "$i have permissions";
              else
                exit 1;
              fi
            else
              exit 1;
            fi
          done
        env:
          EXECUTABLES: ${{ secrets.EXECUTABLES }}

  run_tests:
    name: Runs tests
    runs-on: ubuntu-latest
    needs: check_program_compilation

    steps:
      - uses: actions/checkout@v3

      - name: Compilation with tests_run rule
        run: |
          timeout 120 make tests_run
